services:
  webserver:
    image: caddy:2.7.4-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./src/public:/srv/public
    - caddy_data:/data
    - caddy_config:/config
    - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
      - pgsql
  app:
    image: ghcr.io/adriangl-dev/laravel-app:latest
    container_name: laravel-app
    build: .
    env_file:
      - ./src/.env.production
    restart: unless-stopped
  pgsql:
    container_name: pgsql
    image: postgres
    restart: unless-stopped
    env_file:
      - ./src/.env.production
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # database:
  #   image: mysql:8.1.0
  #   container_name: database
  #   restart: unless-stopped
  #   ports:
  #     - "${DB_PORT}:3306"
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - db_data:/var/lib/mysql/

volumes:
  caddy_data:
  caddy_config:
  postgres_data: