services:
  webserver:
    image: caddy:2.7.4-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./src/public:/srv/public
    - caddy_data:/data
    - caddy_config:/config
    - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
      - database
    networks:
      - laravel_network
  app:
    container_name: laravel-app
    build: .
    image: laravel-app:latest
    restart: unless-stopped
    volumes:
      - ./src:/srv
    networks:
      - laravel_network
  database:
    image: mysql:8.1.0
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: Pass1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - laravel_network

volumes:
  caddy_data:
  caddy_config:
  db_data:

networks:
  laravel_network: