services:
  app:
    container_name: laravel-app
    image: ghcr.io/adriangl-dev/laravel-app:latest
    env_file:
      - ./src/.env.pre
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - pgsql
  pgsql:
    container_name: pgsql
    image: postgres
    restart: unless-stopped
    env_file:
      - ./src/.env.pre
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # database:
  #   image: mysql:8.1.0
  #   container_name: database
  #   restart: unless-stopped
  #   ports:
  #     - "${DB_PORT}:3306"
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - db_data:/var/lib/mysql/

volumes:
  postgres_data: