apiVersion: v1
kind: Service
metadata:
  labels:
    app: laravel-demo
    type: database
  name: mysql-server
  namespace: laravel-demo
spec:
  ports:
    - port: 3306
  selector:
    app: laravel-demo
    type: database