apiVersion: v1
kind: ConfigMap
data:
  Caddyfile: |
    :80 {
      tls internal
      root * /srv/public
      php_fastcgi caddy-php:9000
      file_server
      encode gzip
    }
metadata:
  creationTimestamp: "2023-10-03T13:49:15Z"
  name: caddy-config
  namespace: laravel-demo
  labels:
    app: laravel-demo
    type: caddy-server
