apiVersion: v1
kind: Service
metadata:
  labels:
    app: laravel-demo
    type: webserver
  name: caddy-server
  namespace: laravel-demo
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    type: webserver