apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: laravel-demo
    type: database
  name: mysql-pv-claim
  namespace: laravel-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi