apiVersion: v1
kind: Service
metadata:
  labels:
    type: php
    app: laravel-demo
  name: php-laravel
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: php-socket-port
      port: 9000
  selector:
    app: laravel-demo
    type: php
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: laravel-demo
    type: database
  name: webdata-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laravel-demo
    type: php
  name: php-laravel
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      type: php
      app: laravel-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: php
        app: laravel-demo
    spec:
      containers:
        - image: php-laravel:latest
          imagePullPolicy: IfNotPresent
          name: php-laravel
          ports:
            - containerPort: 9000
              protocol: TCP
              name: php-socket-port
          volumeMounts:
              - name: web-root
                mountPath: /srv
          workingDir: /srv
      restartPolicy: Always
      volumes:
        - name: web-root
          persistentVolumeClaim:
            claimName: webdata-pv-claim